- name: Install nginx on both servers
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
